[workspace]
members = [
    "conversion",
    "convert_to_f32",
    "guess_num",
    "hello_cargo",
    "modules", "owership-entry-level",
    "saturating_arithmetic",
    "structs", "temp",
    "variables",
    "visibility",
]

resolver = "1"
